name: Validate changes terraform

on:
  push:
    branches:
      - 'main'
jobs:
  fmt-check:
    runs-on: ubuntu-latest
    name: Check error syntax of terraform files
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1
        with:
          path: terraform

  validate:
    runs-on: ubuntu-latest
    name: Validate terraform conf files
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: terraform validate
        uses: dflook/terraform-validate@v1
        with:
          path: terraform
